osx_image: xcode8
language: objective-c

env:
  - SAMPLE=admob  

rvm: 2.3.1
before_install:
  - gem uninstall cocoapods -a
  - gem install cocoapods -v '1.0.1'
  - ./travis_script.sh
  - gem install xcodeproj
  - ruby info_script.rb $SAMPLE

script: xcodebuild -workspace $SAMPLE/$SAMPLEexample.xcworkspace
  -scheme $SAMPLEexample
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 7'
  build
  test
  ONLY_ACTIVE_ARCH=YES
  CODE_SIGNING_REQUIRED=NO
