osx_image: xcode8.1
language: objective-c
cache:
  - bundler
  - cocoapods

podfile: admob/Podfile
env: SAMPLE=AdMob

matrix:
  include:
  - podfile: analytics/Podfile
    env: SAMPLE=Analytics
  - podfile: authentication/Podfile
    env: SAMPLE=Authentication
  - podfile: config/Podfile
    env: SAMPLE=Config
  - podfile: crashreporting/Podfile
    env: SAMPLE=CrashReporting
  - podfile: database/Podfile
    env: SAMPLE=Database
  - podfile: dynamiclinks/Podfile
    env: SAMPLE=DynamicLinks
  - podfile: invites/Podfile
    env: SAMPLE=Invites
  - podfile: messaging/Podfile
    env: SAMPLE=Messaging
  - podfile: storage/Podfile
    env: SAMPLE=Storage

rvm: 2.3.1
before_install:
  - export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 7 (10.1" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
  - echo $IOS_SIMULATOR_UDID
  - open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID
  - gem uninstall cocoapods -a
  - gem install cocoapods -v '1.1.1'
  - cd $SAMPLE
  - pod install --repo-update
  - cp ../mock-GoogleService-Info.plist ./GoogleService-Info.plist
  - sed -i '' '/<key>BUNDLE_ID</{n;s/id/com.google.firebase.quickstart.'$SAMPLE'Example/;}' GoogleService-Info.plist
  - sed -i '' 's/YOUR_REVERSED_CLIENT_ID/com.googleusercontent.apps.123456789000-hjugbg6ud799v4c49dim8ce2usclthar/' "$SAMPLE"Example/Info.plist
  - cd -
  - gem install xcodeproj
  - ruby info_script.rb $SAMPLE

script: travis_retry xcodebuild -workspace ${SAMPLE}/${SAMPLE}Example.xcworkspace
  -scheme ${SAMPLE}Example
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 7'
  build
  test
  ONLY_ACTIVE_ARCH=YES
  CODE_SIGNING_REQUIRED=NO
