osx_image: xcode8
language: objective-c
cache:
  - bundler
  - cocoapods
podfile: $SAMPLE/Podfile

env:
  - SAMPLE=AdMob
  - SAMPLE=Analytics
  - SAMPLE=Authentication
  - SAMPLE=Config
  - SAMPLE=Crash
  - SAMPLE=Database
  - SAMPLE=DynamicLinks
  - SAMPLE=Invites
  - SAMPLE=Messaging
  - SAMPLE=Storage

rvm: 2.3.1
before_install:
  - gem uninstall cocoapods -a
  - gem install cocoapods -v '1.0.1'
  - cd $SAMPLE
  - pod install --repo-update
  - cp ../mock-GoogleService-Info.plist ./GoogleService-Info.plist
  - sed -i '' '/<key>BUNDLE_ID</{n;s/id/com.google.firebase.quickstart.'$SAMPLE'Example/;}' GoogleService-Info.plist
  - cd -
  - gem install xcodeproj
  - ruby info_script.rb $SAMPLE

script: xcodebuild -workspace ${SAMPLE}/${SAMPLE}Example.xcworkspace
  -scheme ${SAMPLE}Example
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 7'
  build
  test
  ONLY_ACTIVE_ARCH=YES
  CODE_SIGNING_REQUIRED=NO
