osx_image: xcode9.3

language: objective-c
cache:
  - bundler
  - cocoapods

matrix:
  include:
  - podfile: admob/Podfile
    env: SAMPLE=AdMob
  - podfile: analytics/Podfile
    env: SAMPLE=Analytics
  - podfile: authentication/Podfile
    env: SAMPLE=Authentication
  - podfile: config/Podfile
    env: SAMPLE=Config
  - podfile: crashreporting/Podfile
    env: SAMPLE=CrashReporting
  - podfile: database/Podfile
    env: SAMPLE=Database
  - podfile: dynamiclinks/Podfile
    env: SAMPLE=DynamicLinks
  - podfile: invites/Podfile
    env: SAMPLE=Invites
  - podfile: messaging/Podfile
    env: SAMPLE=Messaging
  - podfile: storage/Podfile
    env: SAMPLE=Storage

rvm: 2.3.1
before_install:
  - npm install ios-sim -g
  - ios-sim start --devicetypeid "com.apple.CoreSimulator.SimDeviceType.iPhone-8-Plus, 11.3"
  - cd $SAMPLE
  - bundle install
  - gem install xcpretty
  - bundle exec pod install --repo-update
  - cp ../mock-GoogleService-Info.plist ./GoogleService-Info.plist
  - sed -i '' '/<key>BUNDLE_ID</{n;s/id/com.google.firebase.quickstart.'$SAMPLE'Example/;}' GoogleService-Info.plist
  - sed -i '' 's/YOUR_REVERSED_CLIENT_ID/com.googleusercontent.apps.123456789000-hjugbg6ud799v4c49dim8ce2usclthar/' "$SAMPLE"Example/Info.plist
  - gem install xcodeproj
  - ruby ../info_script.rb $SAMPLE
  - cd -

script: ./test.sh

branches:
  only:
    - master
